// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Title_with_String_Length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Title_with_String_Length));
        
        string IMigrationMetadata.Id
        {
            get { return "201410090632159_Title_with_String_Length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
