// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Price_Range1to200_DataType_Currency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Price_Range1to200_DataType_Currency));
        
        string IMigrationMetadata.Id
        {
            get { return "201410090646173_Price_Range1to200_DataType_Currency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
