// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Rating_maxLen5_RegularExpression : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rating_maxLen5_RegularExpression));
        
        string IMigrationMetadata.Id
        {
            get { return "201410090648442_Rating_maxLen5_RegularExpression"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
