// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Genre_32MaxLen_RegExAndRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Genre_32MaxLen_RegExAndRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201410090643410_Genre_32MaxLen_RegExAndRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
